SELECT * FROM products;
SELECT * FROM customers;
SELECT * FROM markets;
SELECT * FROM date;
SELECT * FROM transactions;
SELECT COUNT(*) FROM transactions;
SELECT COUNT(*) FROM markets;
SELECT COUNT(DISTINCT markets_name) FROM markets;
SELECT COUNT(DISTINCT product_code) FROM transactions;
SELECT COUNT(DISTINCT product_code) FROM products;
SELECT COUNT(DISTINCT customer_code) FROM customers;
SELECT * FROM transactions WHERE market_code = 'Mark001';
SELECT COUNT(*) FROM transactions WHERE market_code = 'Mark006';
SELECT DISTINCT product_code FROM transactions WHERE market_code = 'Mark001';
SELECT COUNT(DISTINCT product_code) FROM transactions INNER JOIN markets ON transactions.market_code = markets.markets_code JOIN date ON transactions.order_date = date.date WHERE year = '2020' AND markets_name = 'Bhopal';
SELECT SUM(sales_amount) AS Revenue FROM transactions;
SELECT * FROM transactions INNER JOIN date ON transactions.order_date = date.date WHERE date.year = 2020;
SELECT SUM(sales_amount) AS Revenue_2020 FROM transactions INNER JOIN date ON transactions.order_date = date.date WHERE date.year = 2020;
SELECT SUM(sales_amount) AS Revenue_2019 FROM transactions INNER JOIN date ON transactions.order_date = date.date WHERE date.year = 2019;
SELECT SUM(sales_amount) AS Revenue_2020_Jan FROM transactions INNER JOIN date ON transactions.order_date = date.date WHERE date.year = 2020 AND date.month_name = 'January';
SELECT * FROM transactions INNER JOIN date ON transactions.order_date = date.date WHERE date.year = 2020 AND transactions.market_code = 'Mark006';
SELECT * FROM transactions WHERE currency = 'USD';
SELECT * FROM transactions WHERE sales_amount < 1;
SELECT DISTINCT t.product_code FROM transactions t LEFT JOIN products p ON t.product_code = p.product_code WHERE p.product_code IS NULL ORDER BY product_code;
INSERT INTO products (product_code,product_type) VALUES ('Prod280','Unknown'), ('Prod281','Unknown'), ('Prod282','Unknown'), ('Prod283','Unknown'), ('Prod284','Unknown'), ('Prod285','Unknown'), ('Prod286','Unknown'), ('Prod287','Unknown'), ('Prod288','Unknown'), ('Prod289','Unknown');     
INSERT INTO products (product_code,product_type) VALUES ('Prod290','Unknown'), ('Prod291','Unknown'), ('Prod292','Unknown'), ('Prod293','Unknown'), ('Prod294','Unknown'), ('Prod295','Unknown'), ('Prod296','Unknown'), ('Prod297','Unknown'), ('Prod298','Unknown');
INSERT INTO products (product_code,product_type) VALUES ('Prod300','Unknown'), ('Prod301','Unknown'), ('Prod302','Unknown'), ('Prod303','Unknown'), ('Prod304','Unknown'), ('Prod305','Unknown'), ('Prod306','Unknown'), ('Prod307','Unknown'), ('Prod308','Unknown'), ('Prod309','Unknown');
INSERT INTO products (product_code,product_type) VALUES ('Prod310','Unknown'), ('Prod311','Unknown'), ('Prod312','Unknown'), ('Prod313','Unknown'), ('Prod314','Unknown'), ('Prod315','Unknown'), ('Prod316','Unknown'), ('Prod317','Unknown'), ('Prod318','Unknown'), ('Prod319','Unknown');
INSERT INTO products (product_code,product_type) VALUES ('Prod320','Unknown'), ('Prod321','Unknown'), ('Prod322','Unknown'), ('Prod323','Unknown'), ('Prod324','Unknown'), ('Prod325','Unknown'), ('Prod326','Unknown'), ('Prod327','Unknown'), ('Prod328','Unknown'), ('Prod329','Unknown');
INSERT INTO products (product_code,product_type) VALUES ('Prod330','Unknown'), ('Prod331','Unknown'), ('Prod332','Unknown'), ('Prod333','Unknown'), ('Prod334','Unknown'), ('Prod335','Unknown'), ('Prod336','Unknown'), ('Prod337','Unknown'), ('Prod338','Unknown'), ('Prod339','Unknown');
SELECT DISTINCT market_code FROM transactions WHERE product_code = 'Prod318' ORDER BY market_code;
SELECT product_code, markets_name,sales_amount, profit_margin,cost_price FROM transactions JOIN markets ON transactions.market_code = markets.markets_code JOIN date ON transactions.order_date = date.date WHERE year = '2020' AND product_code = 'Prod279';
SELECT COUNT(DISTINCT product_code) FROM transactions JOIN date ON transactions.order_date = date.date WHERE year = '2020';